### ISSUE TITLE
bag_of_words primitive fails when receives only one column as inputs

### ISSUE THREAD

**Issue by roquelopez** [tonyjo/ubc_primitives#2]
I'm getting this error:

```
Traceback (most recent call last):
  File "/src/d3m/d3m/runtime.py", line 1008, in _do_run_step
    self._run_step(step)
  File "/src/d3m/d3m/runtime.py", line 998, in _run_step
    self._run_primitive(step)
  File "/src/d3m/d3m/runtime.py", line 873, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/src/d3m/d3m/runtime.py", line 974, in _call_primitive_method
    raise error
  File "/src/d3m/d3m/runtime.py", line 970, in _call_primitive_method
    result = method(**arguments)
  File "/src/d3m/d3m/primitive_interfaces/transformer.py", line 71, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs)
  File "/src/d3m/d3m/primitive_interfaces/base.py", line 568, in _fit_multi_produce
    produce_results = self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, **kwargs)
  File "/src/d3m/d3m/primitive_interfaces/base.py", line 465, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/src/ubc-primitives/primitives_ubc/bow/bag_of_words.py", line 180, in produce
    outputs = inputs.remove_columns(attribute_columns)
  File "/src/d3m/d3m/container/pandas.py", line 262, in remove_columns
    raise ValueError("Removing columns would have removed the last column.")
ValueError: Removing columns would have removed the last column.
```
The problem happens in `inputs.remove_columns(attribute_columns)` when inputs contain only one column. The method `remove_columns` raises an exception if no columns would be left after removing columns. See documentation here:  https://gitlab.com/datadrivendiscovery/d3m/-/blob/devel/d3m/container/pandas.py#L237

**Comment by tonyjo** [comment]
Fixed in merge #8
